import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./Components/Header";
import NextAuthProvider from "@/provider/NextAuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex flex-col overflow-x-hidden items-center justify-between">
          <Header />
          <NextAuthProvider> {children}</NextAuthProvider>
        </main>
      </body>
    </html>
  );
}
