import "./globals.css";
import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import Header from "./Components/Header";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ weight: ["400", "800"], subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <main className="flex flex-col overflow-x-hidden items-center justify-between">
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
